# src/main/resources/application.properties

# ── Servidor ──────────────────────────────────────────────────────────────────
server.port=8080

# ── Thymeleaf (View) ──────────────────────────────────────────────────────────
# Cache desligado em desenvolvimento — recarrega templates sem reiniciar
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
